### ISSUE TITLE
Remove the unlock button from CE-201 submit review page

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#100]
**Describe the bug**
There shouldn't have any unlock button on the CE-201 review page

**Comment by sanjiva** [comment]
Flow of execution:
- User selects district -> pd -> cc
- User opens empty 201 form
- Fills it in
- Clicks "Next"
- Looks at filled form (as a report) to review to make sure its correct
- If ok, presses "Submit"
- If not presses "Back" to edit

Later, if unlock is needed:
- User selects district -> pd -> cc
- Clicks "Unlock"
- Edit
- and continue form 'Clicks "Next"' above

**Comment by pawan-manishka** [comment]
Removed the Unlocked button from CE-201 submit review page.
