### ISSUE TITLE
Create dialog/ warning when you press the back button to warn users they will lose data if they proceed. 

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#114]
- Back button on browser and on screen should behave the same way. 
- When you browser back is pressed, you should get the dialog / warning message. 
-  Message should state "Warning: entered data will be lost if you proceed"

**Comment by RavinduHasithanjana** [comment]
<img width="1678" alt="Screen Shot 2019-10-22 at 4 14 26 PM" src="https://user-images.githubusercontent.com/17488349/67278755-3bd5c980-f4e7-11e9-8c01-c86d5387411f.png">

**Comment by RavinduHasithanjana** [comment]
Small issue of the button not working and not setting the alert for all the forms
