### ISSUE TITLE
Multiple ballot box IDs are not saved in CE-201

### ISSUE THREAD

**Issue by dinukadesilva** [ECLK/results-tabulation-ui#119]
**Describe the bug**

**To Reproduce**
1. Go to CE-201 form
2. Enter more than one ballot IDs.
3. Click next
4. Only one ballot box is shown.

**Expected behavior**
It should display all the ballot boxes.

**Comment by umayangag** [comment]
This issue is not valid anymore since the ballot IDs inputs were removed
