### ISSUE TITLE
Next buton in PRE-41 "Next" needs clicking twice

### ISSUE THREAD

**Issue by dinukadesilva** [ECLK/results-tabulation-ui#128]
**Describe the bug**
After filling the PRE-41 tallysheet, it waits till clicking twice or thrice.

**To Reproduce**
1. Go to PRE-41 form
2. Fill the data
3. Click "Next"
4. Nothing happens
3. Click "Next"
4. Nothing happens
3. Click "Next"
4. Navigates to the verification page

**Expected behavior**
It should show something like a spinner while processing and should not make the user clicking next button more than once.

**Comment by RavinduHasithanjana** [comment]
Done for pre 41
