### ISSUE TITLE
Edit option not working in CE-201

### ISSUE THREAD

**Issue by YujithIsura** [ECLK/results-tabulation-ui#169]
Edit option not working in CE-201 form  have to edit all records from the beginning

**To Reproduce**
1. Go to  CE-201 form
2. Fill the form with wrong entry
3. Click on unlock button
4. Have to enter all the data again from the beginning
 

**Expected behavior**
User should be able to edit specific record successfully

**Comment by nshamit** [comment]
relates to #170 and #171
