### ISSUE TITLE
CE201, PRE41, 201PV, 41PV Data Entry Flow

### ISSUE THREAD

**Issue by manuraliyanawatte** [ECLK/results-tabulation-ui#170]
Below is the process flow for the Data Entry person:
[Form View]
1. Enters Data
2. Press "NEXT"
[HTML View]
Checks the entered data:

If OK then presses "LOCK & SUBMIT"

If there is a change:
[HTML View]
- [ ] Press "EDIT" button
[Form View]
Make necessary changes
Press "NEXT"
[HTML View]
Then finally  "LOCK & SUBMIT"

Upon submission, the user is directed to the data entry landing page

**Comment by pawan-manishka** [comment]
Changed the Data Entry Flow. Done.
