### ISSUE TITLE
CE201, PRE41, 201PV, 41PV Verifier Process Flow

### ISSUE THREAD

**Issue by manuraliyanawatte** [ECLK/results-tabulation-ui#171]
Below is the process flow for the Verifier person:

- [ ] Add a "VERIFY" button
Clicks the verify button next to e.g. CE201/PRE 41/ CE201 PV/ PRE 41 PV 
Selects a particular Tally sheet:
[HTML View]
Checks the entered data:
[HTML View]
If OK then presses "LOCK & SUBMIT"

- [ ] Add a "LOCK" button

If there is a change:
[HTML View]
 Press "EDIT" button
Make necessary changes
[Form View]
Press "NEXT"

[HTML View]
Then finally "LOCK & SUBMIT"

Upon submission, the user is directed to the data entry landing page

**Comment by nshamit** [comment]
Flow change in new UI
