### ISSUE TITLE
In reports view, show when 30 PDs, 30 PVs, 30 EDs, All Island ED and All Island reports are ready to be generated. 

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#174]
In reports view for 30 PD, 30 PV, 30 ED, All Island ED and All Island reports should have the following:

- [x] 1. Allow partial results view through a "VIEW" button

- [x] 2. Show complete results through a "GENERATE" button 

- [x] 3. Have a button to return to the Reports home page. 

- [ ] 4. Show which reports are "pending" results and from where.  e.g. which PDs need to be completed to generate an ED report.  @dinukadesilva

**Comment by pawan-manishka** [comment]
1,2 and 3 tasks are done.

 Need backend API to show which reports are "pending" results.

**Comment by nshamit** [comment]
done
