### ISSUE TITLE
CE 201 PV needs to have rows differentiated through grey/ white color to help data entry user focus on each row

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#175]
Current data entry form view doesn't have the grey/white rows. Needs to look similar to CE 201, PRE 41 and PRE 41PV

**Comment by pawan-manishka** [comment]
Done.

<img width="1405" alt="Screen Shot 2019-10-28 at 12 49 35 AM" src="https://user-images.githubusercontent.com/19957254/67640036-6d9ec400-f91d-11e9-81f6-4cfa5f5be3ef.png">
