### ISSUE TITLE
PRE 41 PV ui says PRE 41 and breadcrumb says "votes PRE-41" instead of "PRE 41 PV"

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#178]
![Screen Shot 2019-10-26 at 19 40 38](https://user-images.githubusercontent.com/44461004/67620821-985b2080-f828-11e9-9773-ac51a2dc8265.jpg)

**Comment by pawan-manishka** [comment]
Done.

<img width="1440" alt="Screen Shot 2019-10-27 at 11 45 03 PM" src="https://user-images.githubusercontent.com/19957254/67639303-3677e500-f914-11e9-9f57-f0705eea7c1f.png">
