### ISSUE TITLE
Data entry UI PRE 34 CO and PRE 34 CO PV

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#210]
- [x] 1. Candidate 1 (two numbers and total), Candidate 2 (two numbers and total) on x axis (top row)

- [x] 2. Add to 34 CO PV to home screen. 

- [x] 3. Add Ballot Papers "not counted" column

- [x] 4. Remaining ballot papers 

- [x] 5. Change Grand Total to "Total [Candidate 1] and Total [Candidate 2]

- [x] 6. Change Total (at the end) to Grand Total [C1 + C2]

![Screen Shot 2019-11-09 at 23 15 08](https://user-images.githubusercontent.com/44461004/68532697-cf602480-0346-11ea-8e3e-25c4901a0ba8.jpg)

**Comment by umayangag** [comment]
these issues has been fixed in pull request #257
