### ISSUE TITLE
Create PRE 34 report view (table is fine) 

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#214]
- Create a PRE 34 table which is the final total of preferences for Candidate 1 and Candidate 2. 

Process:

- data for PRE 34 CO is entered
- generates PRE 34 I RO (polling division)
- generates PRE 34 II RO (electoral district)
- generates PRE 34 (electoral district)
- totals are included in the revised 30 ED w/ the second preference totals 
- totals are included in the revised All Island ED and All Island Final Results

**Comment by umayangag** [comment]
@nshamit Dinuka is working on this already. Assign this to him please
