### ISSUE TITLE
Create 34 II RO report at district level (total of the 34 I RO forms).

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#225]
- [ ] Create 34 II RO report at electoral district level (total of the 34 I RO forms). Table view is fine. doesn't need to be sophisticated. 

- [x] Add to home screen

**Comment by umayangag** [comment]
@nshamit Dinuka is working on this already. Assign this to him please

**Comment by nshamit** [comment]
Decided not to do the 34 II RO
