### ISSUE TITLE
CE-201: If there are more than 2 ballot boxes - only the last one is shown in the report ce201

### ISSUE THREAD

**Issue by Hakim369** [ECLK/results-tabulation-ui#25]
Clarification:
1 - When 2 ballot box numbers are entered on the data entry screen only the last one is shown in the report.
2 - Requirement is to show both ballot box numbers in the report

**Comment by sanjiva** [comment]
Backend is not receiving the proper list of ballot boxes from the front end.

**Comment by nshamit** [comment]
We do not need to show ballot box ID numbers in the CE -201 for the Presidential Election. 
We only need to show these fields in the normal CE 201 report/html view filled in:

1. Polling District
2. Polling station 
3. Box Count.

**Comment by RavinduHasithanjana** [comment]
Because of the 201 requirement changes, this issue is not valid at the moment
