### ISSUE TITLE
Preferences data entry listed in non-preferences list in home page. 

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#258]
![Screen Shot 2019-11-09 at 21 16 55](https://user-images.githubusercontent.com/44461004/68531232-4e992c80-0336-11ea-973f-35e565383ddb.jpg)

Data Entry should read:

- CE 201 PV
- PRE 41 PV
- CE 201
- PRE 41

Preferences should read:
PRE 34 CO PV
PRE 34 CO

**Comment by umayangag** [comment]
this issue has been fixed
