### ISSUE TITLE
Generate results release letters for 30 ED, All Island ED and All Island Results Reports

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#56]
**Describe the solution you'd like**

- [ ] 1. On each of the following reports we need to have 3 signatures. 

- 30 ED
- All Island ED
- All Island

Signatures must be as follows from **left to right:**

1. Mr. N.J. Abeysekara (PC)
Member, Election Commission of Sri Lanka

2. Mr. Mahinda Deshapriya
Chairman, Election Commission of Sri Lanka

3. Prof.S. Rathnajeevan H.Hoole
Member, Election Commission of Sri Lanka

- [ ] 2. Include checked by and verified by for all 3.

**Comment by sanjiva** [comment]
This is not a report, but rather a letter that gets generated, printed, signed, scanned and used in results release process.

**Comment by dinukadesilva** [comment]
This is to be fixed on https://github.com/ECLK/results-tabulation-api/issues/213
