### ISSUE TITLE
CE 201 and PRE 41 forms - data entry rows are two different colors 

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#59]
**Describe the solution you'd like**
To ensure that data entry operators stay focused:
1. one row should be white
2. one row should be light grey

**Comment by pawan-manishka** [comment]
Done. Added different row colours for PRE 41 and CE201.

PRE 41
<img width="1440" alt="Screen Shot 2019-10-21 at 12 38 10 PM" src="https://user-images.githubusercontent.com/19957254/67184500-90067e00-f401-11e9-90c0-457750f66e30.png">

CE 201
<img width="1439" alt="Screen Shot 2019-10-21 at 12 47 27 PM" src="https://user-images.githubusercontent.com/19957254/67184549-a8769880-f401-11e9-85a2-1664821cd59c.png">
