### ISSUE TITLE
Name of election, electoral district, polling division and counting hall - details should be shown in the data entry UIs for CE 201, PRE 41, CE 201 PV and PRE 41 PV

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#63]
**Describe the solution you'd like**
Name of election, electoral district, polling division and counting hall - details should be shown in the review page

**Comment by pawan-manishka** [comment]
Added electoral district, polling division and counting hall for PRE 41.

<img width="1439" alt="Screen Shot 2019-10-22 at 5 29 48 PM" src="https://user-images.githubusercontent.com/19957254/67283984-56617000-f4f2-11e9-8b01-212f68d4d8ee.png">

**Comment by pawan-manishka** [comment]
Added electoral district, polling division and counting hall for CE 201.

<img width="1432" alt="Screen Shot 2019-10-22 at 6 19 00 PM" src="https://user-images.githubusercontent.com/19957254/67287353-94619280-f4f8-11e9-9ec6-21a2079e2f95.png">
