### ISSUE TITLE
After data entry, hitting the browser back button takes you random pages you never went to before. 

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#64]
**Describe the bug**

**To Reproduce**
1. Go to CE 201 data entry
2. Click on Puttalam
3. Select Wennapuwa polling division 
4. Select counting center 40.
5. Go to the data entry form. 
6. Hit the browser back button -> PRE-41 - Counting Hall No : 1

**Expected behavior**
Should be directed to the landing page for data entry.

**Comment by pawan-manishka** [comment]
Done. Added Push and goBack to the routes.
