### ISSUE TITLE
Improve 201 validations

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#71]
**Describe the solution you'd like**
Fields will have a default 0. However, when those same fields have been edited and do not contain a value, the validation should show next to the appropriate field(s).

**Comment by nshamit** [comment]
This should be for the difference box in CE 201. Instead of autocalculating, see if we can produce a message.

**Comment by sanjiva** [comment]
- Make box count total mandatory
- Default zero for everything

**Comment by sanjiva** [comment]
- Make box count total and spoilt ballots count mandatory
- That is, DO NOT make those fields default zero
- Make all other fields default zero
- Validate on client side

**Comment by nshamit** [comment]
Updated after EC conversation. Need to proceed w/ the following:

1. Make box count total mandatory
2. That is, DO NOT make that field (box count field) default zero
3. Make all other fields default zero
4. Validate on client side 

only include these fields in the normal CE 201 html/report view:
1. Polling district
2. Polling station 
3. Box count.
