### ISSUE TITLE
 Mapping of PD and Polling station fine but Counting center is incorrect. 

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#76]
**To Reproduce**
1. Select ED ->PD-> CC. Puttalam-> Anamaduwa-> CC 10. 
2. See incorrectly mapped PD and polling station 

**Expected behavior**
You should see CC 10 but Counting center is incorrect. It showed 175. 
Likewise, CC 183.

**Comment by nshamit** [comment]
![CC error](https://user-images.githubusercontent.com/44461004/67138830-c956b680-f266-11e9-9784-a867928f9524.jpeg)

**Comment by RavinduHasithanjana** [comment]
@nshamit  the issue was fixed by @dinukadesilva

**Comment by sanjiva** [comment]
@RavinduHasithanjana please indicate the PR and close this issue if its already fixed.
