### ISSUE TITLE
allow 5 ballot boxes in the CE 201 form to accommodate larger no. of candidates for Presidential 2019

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#90]

**Comment by RavinduHasithanjana** [comment]
We have fixed the issue but remember @nshamit even if the UI changes these are not been seen in the report 
![WhatsApp Image 2019-10-19 at 18 11 59](https://user-images.githubusercontent.com/17488349/67145439-561d6680-f29f-11e9-8665-234908f15cb9.jpeg)

**Comment by RavinduHasithanjana** [comment]
@nshamit sorry wrong screenshot
