### ISSUE TITLE
Numerical values are not validated on PRE-41

### ISSUE THREAD

**Issue by dinukadesilva** [ECLK/results-tabulation-ui#95]
**Describe the bug**
The party count text field in PRE-41 is allowed to type any character but no any validations incorporated.

**Expected behavior**
It should validate the input and prompt the user to correct it.

**Comment by sanjiva** [comment]
Allow typing and char but beep or do something to show invalid input.

**Comment by RavinduHasithanjana** [comment]
<img width="1650" alt="Screen Shot 2019-10-22 at 3 27 11 PM" src="https://user-images.githubusercontent.com/17488349/67275534-7425d980-f4e0-11e9-8ee7-c3005707d24d.png">

Made the no of votes in figures mandatory to enter only numerical characters not allowing user to enter any other char other than numericals
