### ISSUE TITLE
in rejected votes, include rejected votes word in sinhala next to english so people understand what value needs to be typed in,. 

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#97]

**Comment by sanjiva** [comment]
Basically add labels in Sinhala.

**Comment by sanjiva** [comment]
And Tamil

**Comment by RavinduHasithanjana** [comment]
Issue Fixed  
<img width="1667" alt="Screen Shot 2019-10-21 at 2 56 32 PM" src="https://user-images.githubusercontent.com/17488349/67193617-360eb400-f413-11e9-8b64-4985d33c8827.png">

**Comment by sanjiva** [comment]
Please refer to this in the commit message - but since u've committed please put a comment with a link to the commit and re-close it.

**Comment by nshamit** [comment]
Ravindu, can we also:

- [ ] 1. highlight this rejected votes row in a color - grey /purple so they notice it.

- [ ] 2. have a validation message for this if rejected votes is not filled in?

**Comment by RavinduHasithanjana** [comment]
https://github.com/ECLK/results-tabulation-ui/commit/6979f32a310296c3fda968430723b8489ce9c4d9
