### ISSUE TITLE
include a button or redirection from the tally sheets screen to the home screen after all data entry / verification by an officer is complete

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#98]

**Comment by sanjiva** [comment]
Can be solved by putting two buttons on top:
- Data Entry (brings you to the top level data entry page)
- Reports (brings you to top level reports page)

**Comment by RavinduHasithanjana** [comment]
<img width="1680" alt="Screen Shot 2019-10-22 at 11 54 36 AM" src="https://user-images.githubusercontent.com/17488349/67262555-e1c30d00-f4c2-11e9-9ef2-3cb5a676c8b2.png">
