### ISSUE TITLE
41 data entry form has the candidate name and party name in the wrong order

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#99]
Report shows it correctly but the data entry form has it backwards.

**Comment by pawan-manishka** [comment]
Changed the order in data entry form. Done

**Comment by pawan-manishka** [comment]
<img width="1440" alt="Screen Shot 2019-10-21 at 12 37 27 PM" src="https://user-images.githubusercontent.com/19957254/67185078-ab25bd80-f402-11e9-98c4-eeccf7315e1a.png">
